name: Update Fortnite Item Shop Image

on:
  workflow_dispatch:  # Позволяет запускать workflow вручную
  schedule:
    - cron: '0 19 * * *'  # Запуск каждый день в 16:00 по Минску

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Подключаем код из репозитория

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Установим Node.js версии 16 и выше

    - name: Install dependencies
  run: |
    npm install
    npm install form-data  # Если отдельно нужно установить form-data

    - name: Run script
      run: node index_fnapi.io.js  # Запускаем скрипт для генерации и отправки изображения

env:
      FNAPI_IO_TOKEN: ${{ secrets.FNAPI_IO_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
